env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended

rules:
  eqeqeq: error
  no-console: warn
  no-unused-vars: [error, {vars: all, args: none, ignoreRestSiblings: false}]
  no-warning-comments: warn
