node_js:
- '7'
dist: trusty
script:
- npm install
- npm run build
- mv web-ext-artifacts/speak-to-me-1.0.zip web-ext-artifacts/speak-to-me-1.0.xpi
deploy:
  provider: releases
  api_key:
    secure: Xg3Ju8R9VaZYChPkoz/MVij/RH0/6vSEc1I0SbxwhrVSIO8K01QXFPwKk+AF+eAl5qsNnDZgdS63h+6v4AUG9EMpP15NnI/+FPNeYjnBAB5TSXjvNGdcFLn3E4q4GpIFq4hoI1n7PjPYgJIosWGI3OdO7XO1H0o16+xmWWWGCYaqOrMNvUg2pqSdAkrzqAyeuIQ2rk5Uce4E3545DzgI5UcRkVkD3KRBfgdbwBkAMpfG6RbkG8jbjrYjoD3DsjkuZQscOgSj1o2z3HvcFJkChSvEfxMUnn0tyIrwxzcrBhne7Rzqe/SQg/Wwj5F4dv1qN7XCRJsqOFC80ggYWqSeoin8ajFm6XINaw6h5OgsybIEUsrmJxMYkbwGxkRxsLNJ8WOq9hDHaBNy34y8woIWO3rD7VLHcUUd/OCZ9t2/ZlfkcCsFcFaq3LDwV52hCiawSA9IEMAIhbvTcfZ/iySz3bspvlG/MofBIKV7eYdd2OAyWh26vgsA9d0MYUf/wKVlFT83qHXNNUOl8KspUGEb3RG7zKhCLQn8iiEYRqrdMJmULDx1wy3oRooZPi7Br/hhJtMxMoHXU8q+lgTrQzdmBTJ3a/yb6So8CzQ01r8tbykBVhR89AAfQb/MGaNZIDgMBmHDQGPl296qqCVZZnleKDoZQffjt/8VsoskL7u6DwM=
  file: web-ext-artifacts/speak-to-me-1.0.xpi
  skip_cleanup: true
  on:
    repo: mozilla/speaktome
    tags: true
    branch: master
notifications:
  slack:
    secure: IRaRM+Bd5mGeM+U3S1mchv2Tki0jllZsj1UvQXZ0gUciUEGt08OFGam9l1bE6yIGSqmLASMGp5gU9JA4Mah6vhKrS6ucr79ieLyPT9cr6I/tDvy5OnuR0E3pd5I1VnahQO8vBw5mdJZPCqSRziVDeU61k913JC0g/tqSUHE9ZHlQxCjnoS5T+GCZBx10LHH9gGLm/cZqMBdyvM9wHdLKqhj9KFTHZYDOFMfPsc4S9622VJ0XEtT63yy2djSeN4cOvqNLBdnhpGgZ6vxJjRANr6qtkfqVofAmxYfJAPbQI1Ww1ciEcvFCUQlbWj7y3N1rY0Z457vkgPmCsO0OkjvGWYN0DAbXPSko9aZXQLdLVFW3ynlB9i6W1z8cA+e1pCrU9hNXYjslbxvvmGAjlCHVw4c9Dlim7KU3aaJztE0ya0cQRvze0uIk1cMv/iSD8JAysXhPQAC0DoZOFNsRoeZn0HEDPlWBLHxWRYUdm2yA1Vsj9myi+1r/kvn/fHS+ndh6Hs7VCIfLwPZalCaLGC2rdKyALvTJN3fUXuL6+ZfnEB2kRCPPY+KTKtNTX6rUF44mmsxUMDlNxL1rmAxptcQJKRSckcqjSXYdgiZmcokHIhGNFYql/Kued9cTctl0IIVO1qZZTrizt00AtQ9j6seEmVMhExUF14Am+SPXkWGDVwM=
